/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package transnam;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

public class Transcriber {

    public String getEnglishSurname(String surnamePersian) throws IOException, URISyntaxException {
        readDictionary();
        return lastnamePerEng.get(surnamePersian);
    }

    public String getPersianSurname(String surnameEnglish) throws IOException, URISyntaxException {
        readDictionary();
        return lastnameEngPer.get(surnameEnglish);
    }

    public String getEnglishFirstname(String firstnamePersian) throws IOException, URISyntaxException {
        readDictionary();
        return firstnamePerEng.get(firstnamePersian);
    }

    public String getPersianFirstname(String firstnameEnglish) throws IOException, URISyntaxException {
        readDictionary();
        return firstnameEngPer.get(firstnameEnglish);
    }

    private Map<String, String> firstnameEngPer;
    private Map<String, String> firstnamePerEng;
    private Map<String, String> lastnameEngPer;
    private Map<String, String> lastnamePerEng;

    // If the Transcriber has not loaded the dictionaries into the memory, then
    // Transcriber is not ready.
    private boolean ready = false;

    private void readDictionary() throws IOException, URISyntaxException {
        if (ready) {
            return;
        }
        loadFirstnames();
        loadLastnames();
        ready = true;
    }

    private void loadFirstnames() throws IOException, URISyntaxException {
        String fileName = "firstname.csv";
        URL resource = getClass().getClassLoader().getResource(fileName);
        if (resource == null) {
            throw new IllegalArgumentException(fileName + " not found!");
        }
        File firstnameFile = new File(resource.toURI());
        FileReader reader = new FileReader(firstnameFile);
        BufferedReader buffedReader = new BufferedReader(reader);
        String line = buffedReader.readLine();
        firstnameEngPer = new HashMap<>();
        firstnamePerEng = new HashMap<>();
        while (line != null) {
            String[] pair = line.split(",");
            if (pair.length != 2) {
                throw new IllegalArgumentException("Unexpected line: `" + line + "`");
            }
            firstnameEngPer.put(pair[1], pair[0]);
            firstnamePerEng.put(pair[0], pair[1]);

            // read next line
            line = buffedReader.readLine();
        }
        reader.close();
    }

    private void loadLastnames() throws IOException, URISyntaxException {
        String fileName = "lastname.csv";
        URL resource = getClass().getClassLoader().getResource(fileName);
        if (resource == null) {
            throw new IllegalArgumentException(fileName + " not found!");
        }
        File lastnameFile = new File(resource.toURI());
        FileReader reader = new FileReader(lastnameFile);
        BufferedReader buffedReader = new BufferedReader(reader);
        String line = buffedReader.readLine();
        lastnameEngPer = new HashMap<>();
        lastnamePerEng = new HashMap<>();
        while (line != null) {
            String[] pair = line.split(",");
            if (pair.length != 2) {
                throw new IllegalArgumentException("Unexpected line: `" + line + "`");
            }
            lastnameEngPer.put(pair[1], pair[0]);
            lastnamePerEng.put(pair[0], pair[1]);

            // read next line
            line = buffedReader.readLine();
        }
        buffedReader.close();
        reader.close();
    }
}
