/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package transnam;

import org.junit.Test;
import static org.junit.Assert.*;

public class TranscriberTest {

    @Test
    public void testPersianFirstNameToEnglish() {
        Transcriber t = new Transcriber();
        String result = "not Mehrdad";
        try{
            result = t.getEnglishFirstname("مهرداد");
        } catch(Exception e){
            e.printStackTrace();
        }
        // System.out.println("Result: `" + result + "`");
        assertTrue(result.equals("Mehrdad"));
    }
    
    @Test
    public void testEnglishFirstNameToPersian() {
        Transcriber t = new Transcriber();
        String result = "مهرداد نه";
        try{
            result = t.getPersianFirstname("Mehrdad");
        } catch(Exception e){
            e.printStackTrace();
        }
        // System.out.println("Result: `" + result + "`");
        assertTrue(result.equals("مهرداد"));
    }
}
